language: c

sudo: false

env:
  global:
    - NAME=lua-resty-openidc
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

services:
    - docker

before_install:
  - VERSION=`git describe | grep -oP '[\d\.]+\-\d+'`
  - ROCKSPEC=$NAME-$VERSION.rockspec
  - ROCK=$NAME-$VERSION.src.rock
  - echo $ROCKSPEC && echo $ROCK
  - source .travis/setenv_lua.sh
  - luarocks install Lua-cURL --server=https://luarocks.org/dev
  - luarocks install lunitx
  - luarocks install JSON4Lua

install:
  - luarocks make $ROCKSPEC CFLAGS="-O2 -fPIC -fprofile-arcs" LIBFLAG="-shared"
  - luarocks pack $ROCKSPEC
  # Remove the last line of the Dockerfile so we can build the Docker image with
  # our freshly packed Lua rock:
  - sed -i '$ d' Dockerfile
  # Append COPY command to get the rock into the Docker container:
  - echo "COPY ./${ROCK} /" >> Dockerfile
  # Append RUN command to install the copied rock:
  - echo "RUN /usr/local/openresty/luajit/bin/luarocks install ${ROCK}" >> Dockerfile
  - cat Dockerfile
  - docker build -t $NAME .

script:
  - docker run -d -p 127.0.0.1:80:80 --name $NAME $NAME
  - docker ps | grep $NAME
  # TODO: Add some integration tests that excersice the OAuth and OpenID Connect
  # interface of lua-resty-openidc.

deploy:
  provider: releases
  # The GitHub OAuth Token comes from an environment variable configured on
  # https://travis-ci.org/
  api_key: $GITHUB_OAUTH_TOKEN
  file: $ROCK
  skip_cleanup: true
  on:
    # repo: asbjornu/lua-resty-openidc
    tags: true

after_deploy:
  # The Lua Rocks API key comes from an environment variable configured on
  # https://travis-ci.org/
  - luarocks upload $ROCKSPEC --api-key=$API_KEY

notifications:
  email:
    on_success: change
    on_failure: always