language: c

sudo: false

env:
  global:
    - VERSION=1.2.0-1
    - NAME=lua-resty-openidc
    - ROCKSPEC=$NAME-$VERSION.rockspec
    - ROCK=$NAME-$VERSION.src.rock
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

services:
    - docker

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install Lua-cURL --server=https://luarocks.org/dev
  - luarocks install lunitx
  - luarocks install JSON4Lua

install:
  - luarocks make $ROCKSPEC CFLAGS="-O2 -fPIC -fprofile-arcs" LIBFLAG="-shared"
  - luarocks pack $ROCKSPEC
  # Remove the last line of the Dockerfile so we can build the Docker image with
  # our freshly packed Lua rock:
  - sed -i '$ d' Dockerfile
  # Append COPY command to get the rock into the Docker container:
  - echo "COPY ./${ROCK} /" >> Dockerfile
  # Append RUN command to install the copied rock:
  - echo "RUN /usr/local/openresty/luajit/bin/luarocks install ${ROCK}" >> Dockerfile
  - cat Dockerfile
  - docker build -t lua-resty-openidc .

script:
  - docker run -d -p 127.0.0.1:80:80 --name lua-resty-openidc lua-resty-openidc
  - docker ps | grep -q lua-resty-openidc
  # TODO: Add some integration tests that excersice the OAuth and OpenID Connect
  # interface of lua-resty-openidc.

after_success:
  # The API key comes from an environment variable configured on
  # https://travis-ci.org/
  - luarocks upload $ROCKSPEC --api-key=$API_KEY

notifications:
  email:
    on_success: change
    on_failure: always