language: c

sudo: false

env:
  global:
    - VERSION=1.2.0-1
    - NAME=lua-resty-openidc
    - ROCKSPEC=$NAME-$VERSION.rockspec
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

services:
    - docker

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install Lua-cURL --server=https://luarocks.org/dev
  - luarocks install lunitx
  - luarocks install JSON4Lua

install:
  - luarocks make $ROCKSPEC CFLAGS="-O2 -fPIC -fprofile-arcs" LIBFLAG="-shared"
  # TODO: We need to inject the current rock of lua-resty-openidc into the Docker container.
  #       It will now just fetch the latest one from luarocks.org.
  - docker build -t lua-resty-openidc .
  - docker run -d -p 127.0.0.1:80:80 --name lua-resty-openidc lua-resty-openidc

script:
  - docker ps | grep -q lua-resty-openidc
  # TODO: Add some integration tests that excersice the OAuth and OpenID Connect
  # interface of lua-resty-openidc.

after_success:
  - luarocks pack $ROCKSPEC
  # The API key comes from an environment variable configured on
  # https://travis-ci.org/
  - luarocks upload $ROCKSPEC --api-key=$API_KEY

notifications:
  email:
    on_success: change
    on_failure: always